### ISSUE TITLE
CocoaPods installation fails

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [NSObjects/OMGRssParser#1]
Hi,

I'm trying to install this library through CocoaPods. Here's my `Podfile`.

```
platform :ios, '8.0'

target 'TopJobs' do
  use_frameworks!

  pod 'OMGRssParser', '~> 0.1'

end
```

It fails with the following error.

> [!] Unable to find a specification for `OMGRssParser (~> 0.1)`

**Comment by NSObjects** [comment]
@Isuru-Nanayakkara 

```
rm ~/Library/Caches/CocoaPods/searchindex.json
pod search OMGRssParser
```
or 
`pod setup`

**Comment by Isuru-Nanayakkara** [comment]
Okay, that worked. Thanks!
